### ISSUE TITLE
Reduce pedersen_hash_chunks_per_generator to be conservative

### ISSUE THREAD

**Issue by ebfull** [zcash-hackworks/sapling-crypto#22]
`pedersen_hash_chunks_per_generator()` currently is 62 -- the number of "chunks" allowed in a segment of a Pedersen hash. I have a test that this number of chunks won't allow for overlap (breaking the injective mapping from input to exponents). However, there may be no need for us to "max out" each scalar, since our inputs generally don't max out every scalar anyway.

We should consider adjusting 62 down while keeping an eye on performance, just to be conservative in case my test is wrong or something else.

**Comment by daira** [comment]
Assume 3-bit windows and 4-bit separation between windows, and let n be the number of chunks per generator. The range of indices is ± {1 .. 3 . 2<sup>4.(n-1)</sup>}. It's easy to prove (the next revision of the spec will prove it) that in the Pedersen hash, the absolute values of the indices are all distinct, provided that 3 . 2<sup>4.(n-1)</sup> <= (s-1)/2. (It is *not* sufficient to have 3 . 2<sup>4.(n-1)</sup> <= s-1.)

(s-1)/2 is between 3 . 2<sup>249</sup> and 3 . 2<sup>250</sup> (it's about 3.62 . 2<sup>249</sup>). So we need 4.(n-1) <= 249, that is n = 62 does work. The 61 in the current (2018.0-beta-9) spec is unnecessarily conservative, and I'm happy to change it to 62 after I've checked the proof.
