### ISSUE TITLE
Ensure BLAKE2s personalization match the spec

### ISSUE THREAD

**Issue by ebfull** [zcash-hackworks/sapling-crypto#39]
These live in `src/constants/` and they're all totally wrong.

**Comment by daira** [comment]
BLAKE2s personalizations:
* CRH<sup>ivk</sup> uses ``Zcashivk``
* MerkleCRH and NoteCommit use ``Zcash_PH`` (for "Pedersen Hash")
* ValueCommit uses ``Zcash_cv``
* Base for MixingPedersenHash uses ``Zcashrho``
* d ↦ g<sub>d</sub> uses ``Zcash_gd`` 
* Base for ak uses ``Zcash_G_``
* Base for rk uses ``Zcash_H_``
* PRF<sup>nr</sup> uses ``Zcashnr\x00`` and ``Zcashnr\x01``.

BLAKE2b personalizations:
* PRF<sup>expand</sup> uses ``Zcash_ExpandSeed``
* KDF<sup>Sapling</sup> uses ``Zcash_SaplingKDF``.

**Comment by ebfull** [comment]
> PRFnr uses Zcashnr\x00 and Zcashnr\x01.

I'm going to use `Zcashnr0` and `Zcashnr1` (all ASCII)

**Comment by daira** [comment]
Well, we decided to change how nr is constructed, so now there's only a need for a single personalization "Zcash_nr".

**Comment by ebfull** [comment]
What about the base for ValueCommit that is for the randomness. `Zcashrcv`?

**Comment by ebfull** [comment]
Same thing for the note commitment. `Zcashrcm`?

**Comment by daira** [comment]
The randomness bases have the same diversifier but "r" as the GroupHash input (M).

**Comment by ebfull** [comment]
I don't want to do that, because it's inconsistent with how any of the other generators are constructed. The group hash input should just be the smallest number that results in a point.

**Comment by daira** [comment]
For all of the generators, there's an input M, followed by a byte holding the smallest number that results in a point. In the case of the Pedersen hash generators for example, M encodes a 4-byte index for the segment number.

**Comment by ebfull** [comment]
Where are the other places this M value is used?

**Comment by ebfull** [comment]
#57 will be changing things to align with what you've specified, but we need to pair to hammer out each detail.

**Comment by daira** [comment]
OK, we have a pairing today where we can do that.
