### ISSUE TITLE
Implement the requested change for depth 32 commitments.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash-hackworks/sapling-crypto#55]
I just requested a change to the Sapling spec in https://github.com/zcash/zips/issues/143 . Assuming there are no blockers for changing the design and updating the spec to match, the implementation needs to be updated to match.

**Comment by daira** [comment]
There are no blockers for updating the spec (the depth is parameterized separately for Sprout and for Sapling), and I'm in favour.

**Comment by daira** [comment]
The spec was updated in 2018.0-beta-15.

**Comment by nathan-at-least** [comment]
Looking at the spec now, I see this in the Constants section:

> MerkleDepth N := 29

I did a quick search for references to `MerkleDepth` but I don't see any distinction for Sprout versus Sapling based on that quick search. How are common constructions with distinct instantiations for Sprout versus Sapling, such as the commitment tree roots and tree states, represented in the spec?

**Comment by str4d** [comment]
@nathan-at-least I replied to the above question [here](https://github.com/zcash/zips/issues/143#issuecomment-374426948). Note that you need to be looking in sapling.pdf, not protocol.pdf.
