### ISSUE TITLE
k-ary AND implementation is suboptimal

### ISSUE THREAD

**Issue by ebfull** [zcash-hackworks/sapling-crypto#7]
Currently the k-ary AND implementation just performs an AND constraint for all of the operations. There is a more efficient recursive approach [outlined by @daira.](https://github.com/zcash/zcash/issues/2234#issuecomment-338985293)

**Comment by daira** [comment]
[This approach](https://github.com/zcash/zcash/issues/3366#issuecomment-401988464) is more efficient still.

**Comment by daira** [comment]
zcash/zcash/issues/3366 suggests to apply the remaining optimizations in the next circuit change (probably NU3).

**Comment by daira** [comment]
We're unlikely to make any further optimizations here.
