### ISSUE TITLE
Pedersen hash circuit implementation can not calculate inputs larger than 63*3*4

### ISSUE THREAD

**Issue by daira** [zcash-hackworks/sapling-crypto#90]
From the QED-it report:
> The circuit implementation in src/circuit/pedersen_hash.rs, when given an input larger than 63\*3\*4 bits, uses up all the 5 generators, as it should. In the next iteration, rather than stopping, it tries to use the unexisting 6th generator. The non-circuit implementation can correctly support inputs up to 63\*3\*5.
>
> While not a pressing issue, since all the inputs around the circuit seem to be less than 63\*3\*4, it does not seem to be the intended behaviour of the implementation.

**Comment by str4d** [comment]
Fixed in https://github.com/zcash/librustzcash/pull/111.
